<a href="https://colab.research.google.com/github/alam292/Alam292/blob/main/Ecommerce_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import  numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

##Data Collection

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving orders.csv to orders.csv

In [ ]:
df = pd.read_csv("orders.csv")

In [ ]:
df

,order_id,customer_id,product_id,seller_id,order_date,order_status,quantity,unit_price,discount,tax_amount,shipping_fee,total_amount,payment_id,payment_method,payment_status,shipping_city,shipping_state,shipping_pincode,delivery_date,customer_rating
0,ORD00000001,CUST030578,PROD0006320,SELL01114,2026-01-03 11:53:24.443541,delivered,3,6119.38,44.14,1162.17,197.02,24035.61,PAY00120243,COD,Completed,Pune,Tamil Nadu,242762.0,2026-09-27 11:22:26.324070,1.0
1,ORD00000002,CUST008134,PROD0006694,SELL00275,2026-01-03 11:54:24.443541,DELIVERED,8,1091.73,17.08,1083.07,489.35,16444.67,PAY00243799,COD,Completed,Noida,Haryana,641740.0,2026-09-27 11:22:26.324096,NaN
2,ORD00000003,CUST018918,PROD0007508,SELL00674,2026-01-03 11:55:24.443541,Delivered,9,2241.77,49.01,402.02,377.91,22191.82,PAY00191877,upi,Completed,Lucknow,Uttar Pradesh,436929.0,2026-10-07 11:22:26.324101,NaN
3,ORD00000004,CUST019490,PROD0001008,SELL00423,2026-01-03 11:56:24.443541,shipped,5,2509.03,5.25,83.49,472.93,3472.73,PAY00032539,Credit Card,Completed,Indore,West Bengal,848774.0,2026-10-02 11:22:26.324104,1.0
4,ORD00000005,CUST009380,PROD0005506,SELL01230,2026-01-03 11:57:24.443541,delivered,6,8852.91,46.81,211.29,193.14,19340.75,PAY00338043,NaN,Completed,Vadodara,Rajasthan,587692.0,2026-09-26 11:22:26.324107,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379495,ORD00379496,CUST031314,PROD0002966,SELL01536,2026-04-02 12:20:24.443541,SHIPPED,1,6586.41,12.60,1460.93,486.94,47030.87,PAY00227888,UPI,Pending,Chennai,Andhra Pradesh,158207.0,2026-10-04 11:22:26.670887,NaN
379496,ORD00379497,CUST017554,PROD0000052,SELL00877,2026-01-26 08:36:24.443541,shipped,10,2053.86,48.25,780.28,424.83,17570.54,PAY00106905,Debit Card,Completed,Surat,West Bengal,439098.0,2026-09-28 11:22:26.410996,NaN
379497,ORD00379498,CUST004270,PROD0005308,SELL00104,2026-02-23 02:42:24.443541,Delivered,7,2215.84,7.89,87.65,226.63,39644.41,PAY00020315,Credit Card,Pending,Kochi,Haryana,143749.0,2026-09-27 11:22:26.518053,3.0
379498,ORD00379499,CUST014634,PROD0004705,SELL00968,NaN,SHIPPED,1,307.62,5.14,1681.09,6.66,27874.52,PAY00375131,Credit Card,Completed,Pune,Gujarat,978790.0,2026-10-04 11:22:26.527057,4.0
379499,ORD00379500,CUST018208,PROD0000765,SELL00764,2026-09-06 14:27:24.443541,Shipped,5,1818.64,9.00,1297.96,386.12,3954.37,PAY00033948,NaN,Completed,Noida,Madhya Pradesh,858450.0,2026-09-02 14:27:24.443541,2.0

##Data Understanding

In [ ]:
df.head()

,order_id,customer_id,product_id,seller_id,order_date,order_status,quantity,unit_price,discount,tax_amount,shipping_fee,total_amount,payment_id,payment_method,payment_status,shipping_city,shipping_state,shipping_pincode,delivery_date,customer_rating
0,ORD00000001,CUST030578,PROD0006320,SELL01114,2026-01-03 11:53:24.443541,delivered,3,6119.38,44.14,1162.17,197.02,24035.61,PAY00120243,COD,Completed,Pune,Tamil Nadu,242762.0,2026-09-27 11:22:26.324070,1.0
1,ORD00000002,CUST008134,PROD0006694,SELL00275,2026-01-03 11:54:24.443541,DELIVERED,8,1091.73,17.08,1083.07,489.35,16444.67,PAY00243799,COD,Completed,Noida,Haryana,641740.0,2026-09-27 11:22:26.324096,NaN
2,ORD00000003,CUST018918,PROD0007508,SELL00674,2026-01-03 11:55:24.443541,Delivered,9,2241.77,49.01,402.02,377.91,22191.82,PAY00191877,upi,Completed,Lucknow,Uttar Pradesh,436929.0,2026-10-07 11:22:26.324101,NaN
3,ORD00000004,CUST019490,PROD0001008,SELL00423,2026-01-03 11:56:24.443541,shipped,5,2509.03,5.25,83.49,472.93,3472.73,PAY00032539,Credit Card,Completed,Indore,West Bengal,848774.0,2026-10-02 11:22:26.324104,1.0
4,ORD00000005,CUST009380,PROD0005506,SELL01230,2026-01-03 11:57:24.443541,delivered,6,8852.91,46.81,211.29,193.14,19340.75,PAY00338043,NaN,Completed,Vadodara,Rajasthan,587692.0,2026-09-26 11:22:26.324107,4.0